#!/bin/bash

if [ $1 != "create" ] && [ $1 != "update" ]
then
  echo "command must be create or update"
  exit 1
fi

if [ $1 == "create" ]
then
  aws cloudformation create-stack --stack-name project2ServerStack --template-body file://server.yml  --parameters file://server-parameters.json --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region=us-east-1
else
  aws cloudformation update-stack --stack-name project2ServerStack --template-body file://server.yml  --parameters file://server-parameters.json --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM" --region=us-east-1
fi
